User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:09:32 for input 34User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:09:34 for input 3421User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:09:35 for input 34213User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:09:39 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:10:31 for input 34
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:10:33 for input 342
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:10:35 for input 3421
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:10:41 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:10:42 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:19:57 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:19:59 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:20:00 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:20:16 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]]
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:25:04 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 13:25:04 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:25:41 for input 32, Cause: No user with specific Id found
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 13:25:42 for input 324, Cause: No user with specific Id found
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:06:17 for input 2, Cause: No user with specific Id found
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:06:19 for input 652, Cause: No user with specific Id found
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 14:06:26 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 14:06:27 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:07:39 for input 23, Cause: No user with specific Id found
14:09:32.445: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:09:32 for input 4, Cause: No user with specific Id found
14:22:50.237: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 14:22:50 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
14:56:36.382: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:56:36 for input 4, Cause: No user with specific Id found
14:56:38.630: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:56:38 for input 4, Cause: No user with specific Id found
14:56:43.600: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:56:43 for input 2, Cause: No user with specific Id found
14:56:44.378: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 14:56:44 for input 2, Cause: No user with specific Id found
17:06:30.831: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:06:30 for input 12, Cause: No user with specific Id found
17:06:35.679: void com.arsh.twitter.services.UserService.deleteById(int) generated Exception at 2021/02/23 17:06:35 for input 5, Cause: User with user id: 5 does not exist.
17:06:42.226: void com.arsh.twitter.services.UserService.deleteById(int) generated Exception at 2021/02/23 17:06:42 for input 3, Cause: User with user id: 3 does not exist.
17:07:20.898: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:07:20 for input 4, Cause: No user with specific Id found
17:07:37.324: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:07:37 for input 3, Cause: No user with specific Id found
17:07:42.271: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:07:42 for input 3, Cause: No user with specific Id found
17:07:47.913: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:07:47 for input 2, Cause: No user with specific Id found
17:07:55.827: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:07:55 for input 3, Cause: No user with specific Id found
17:08:07.309: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:08:07 for input 3, Cause: No user with specific Id found
17:10:04.117: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:10:04 for input 3, Cause: No user with specific Id found
17:12:25.728: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:12:25 for input 2, Cause: No user with specific Id found
17:12:33.382: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/02/23 17:12:33 for input User [id=0, name=Abhinav Sharma, handle=Abi_the_rock, dob=1996-09-19, email=abhigyjan@gmail.com, contact=9876543232, followers=[], followings=[], tweets=[]], Cause: User email Already registered
17:13:16.715: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:13:16 for input 7, Cause: No user with specific Id found
17:13:19.818: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:13:19 for input 6, Cause: No user with specific Id found
17:13:22.011: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:13:22 for input 5, Cause: No user with specific Id found
17:13:28.328: User com.arsh.twitter.services.UserService.findById(int) generated Exception at 2021/02/23 17:13:28 for input 5, Cause: No user with specific Id found
22:56:40.253: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/03/10 22:56:40 for input User [id=0, name=Arsh Rajput, handle=@ARsh, dob=1996-09-19, email=arsh.rajput@tcs.com, contact=7071421404, followers=[], followings=[], tweets=[{title=My first tweet, category=General, time=2021/03/10 22:47:25, description=This is my first tweet writer arsh}]], Cause: User email Already registered
22:56:46.163: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/03/10 22:56:46 for input User [id=0, name=Arsh Rajput, handle=@ARsh, dob=1996-09-19, email=arsh.rajpuft@tcs.com, contact=7071421404, followers=[], followings=[], tweets=[{title=My first tweet, category=General, time=2021/03/10 22:47:25, description=This is my first tweet writer arsh}]], Cause: User contact Already Used by another account
22:56:53.786: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/03/10 22:56:53 for input User [id=0, name=Arsh Rajput, handle=@ARsh, dob=1996-09-19, email=arsh.rajpuft@tcs.com, contact=7071411404, followers=[], followings=[], tweets=[{title=My first tweet, category=General, time=2021/03/10 22:47:25, description=This is my first tweet writer arsh}]], Cause: User handle already taken
22:57:59.174: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/03/10 22:57:59 for input User [id=0, name=Arsh Rajsdafnsdklfdsaput, handle=@AR2sh, dob=1996-09-19, email=arsh.rajpuft@tcs.com, contact=7071411404, followers=[], followings=[], tweets=[{title=My first tweet, category=General, time=2021/03/10 22:47:25, description=This is my first tweet writer arsh}]], Cause: User email Already registered
22:58:06.890: User com.arsh.twitter.services.UserService.save(User) generated Exception at 2021/03/10 22:58:06 for input User [id=0, name=Arsh Rajsdafnsdklfdsaput, handle=@AR2sh, dob=1996-09-19, email=arsh.rajdsafsapuft@tcs.com, contact=7071411404, followers=[], followings=[], tweets=[{title=My first tweet, category=General, time=2021/03/10 22:47:25, description=This is my first tweet writer arsh}]], Cause: User contact Already Used by another account
